CREATE TABLE INVENTORY( ID INT GENERATED BY DEFAULT AS IDENTITY,
                          NAME VARCHAR(100) NOT NULL ,
                          PRICE NUMERIC(8,2) NOT NULL,
                           PRIMARY KEY(ID));